#!/bin/sh
cd "$(dirname "$0")"
rm -rf lib/
rm -rf public/
rm -rf index.d.ts
mkdir lib
mkdir public
mkdir public/css
mkdir public/img
cp -R ./src/img ./public
yarn
gulp stylesProduction
tsc ./src/ts/components/ui/ReactVideoPlay.tsx -d --jsx react --target ES5 --outDir ./lib
cp ./lib/ReactVideoPlay.d.ts ./
mv ReactVideoPlay.d.ts index.d.ts





