#!/bin/sh
cd "$(dirname "$0")"
rm -rf lib/
rm -rf css/
rm -rf index.d.ts
mkdir lib
mkdir css
yarn
gulp stylesProduction
tsc ./src/ts/components/ui/ReactVideoPlay.tsx -d --jsx react --target ES5 --outDir ./lib
cp ./lib/ReactVideoPlay.d.ts ./
mv ReactVideoPlay.d.ts index.d.ts





